### PR TITLE
Add HiLo conversion method

### PR DESCRIPTION
**Pull request by jokruger**
Decimal type has FromHiLo constructor. The opposite method is required so the decimal type can be constructed / deconstructed. Also, ability to convert to {Hi, Lo} pair is important for integrations with other libraries which work with uint64 or uint128 types.

### CODE REVIEW

**Comment by quagmt** [comment]
> ability to convert to {Hi, Lo} pair is important for integrations with other libraries which work with uint64 or uint128 types

Can you elaborate why do you need to convert decimal to another data type? I think libraries that has `uint128` is not that common

**Comment by jokruger** [comment]
> > ability to convert to {Hi, Lo} pair is important for integrations with other libraries which work with uint64 or uint128 types
> 
> Can you elaborate why you need to convert decimal to another data type? I think libraries that has `uint128` is not that common

Example - https://github.com/tigerbeetle/tigerbeetle
It works with uint128. It expects amounts will be represented as 128 bit integer, scaled to required precision. Because it is double entry accounting, internally it requires only Add function for amounts, and only positive values with same scale.

Another example - any external storage where you also want to be able to apply a simple functions like comparison, add, etc. I.e. scaled int is ideal. But int64 is too small. And udecimal in any case targets int128, so why not allow to export to this type?

Another reason is existing FromHiLo constructor. You can build udecimal from Hi/Lo pair... but you cannot deconstruct it back to Hi/Lo.

**Comment by quagmt** [comment]
`FromHiLo` is mainly used for `Fuzz` and tbh I don't expect it to be utilized. Your use case is valid tho. However, I think the name should be `ToHiLo`. Also, can you add some examples to [doc_test.go](https://github.com/quagmt/udecimal/blob/master/doc_test.go) to keep the docs up-to-date?

**Comment by jokruger** [comment]
> `FromHiLo` is mainly used for `Fuzz` and tbh I don't expect it to be utilized. Your use case is valid tho. However, I think the name should be `ToHiLo`. Also, can you add some examples to [doc_test.go](https://github.com/quagmt/udecimal/blob/master/doc_test.go) to keep the docs up-to-date?

done

**Review by quagmt — APPROVED** [review]

**Pull request merged**
